export type PromptSet = {
  labels: string[];
  prompts: string[];
};

export type Deck = {
  id: "love" | "purpose" | "founder" | "friendship" | "money";
  name: string;
  tagline: string;
  blurb: string;
  colors: string[];
  /** Rotating question sets. One set is active per calendar week. */
  weeks: PromptSet[];
};

export const decks: Deck[] = [
  {
    id: "love",
    name: "Love & Marriage",
    tagline: "For two people who want to know each other better",
    blurb: "Twelve prompts on intimacy, memory and the small daily contract of love.",
    colors: ["#a8443c", "#c9744b", "#8f3a52", "#d29a5c", "#7d3b3b", "#b8613f"],
    weeks: [
      {
        labels: [
          "Memory",
          "Confession",
          "Desire",
          "Gratitude",
          "Friction",
          "Future",
          "Truth",
          "Tender",
          "Dare",
          "Origin",
          "Repair",
          "Promise",
        ],
        prompts: [
          "Describe the exact moment you knew I was more than a passing thought — the room, the light, what I was wearing.",
          "Tell me one small thing you've never said out loud because you thought it was too silly to matter.",
          "What's something you want more of from me that you've been quietly waiting for me to notice?",
          "Name three ordinary things I did this month that you're grateful for — no big gestures allowed.",
          "What's a habit of mine that annoys you, and what's the version of it you secretly find endearing?",
          "Describe a Tuesday five years from now, in detail: where we wake up, what breakfast smells like, what we argue about.",
          "Finish honestly: 'The thing I'm most afraid of you finding out about me is…'",
          "Without touching me, tell me the part of me you'd reach for first and why.",
          "Look me in the eyes for 30 seconds without speaking or laughing. Then say the first true sentence that comes.",
          "Retell the story of how we met — but from my side, as you imagine I experienced it.",
          "Recall the last time we hurt each other. What would you do differently if we replayed it tonight?",
          "Make me one promise for the next 30 days that costs you something real.",
        ],
      },
      {
        labels: [
          "Jealousy",
          "Money",
          "Family",
          "Silence",
          "Attraction",
          "Fear",
          "Praise",
          "Habit",
          "Dare",
          "Secret",
          "Repair",
          "Choose",
        ],
        prompts: [
          "When was the last time you felt jealous about me, and what exactly triggered it?",
          "If our money doubled tomorrow, what would you spend it on first — and would you tell me before or after?",
          "What did you learn about love from your parents that you're actively trying to unlearn?",
          "What do you think I'm thinking when I go quiet? Guess out loud, then let me correct you.",
          "Describe something I do that you find attractive that has nothing to do with how I look.",
          "What are you most afraid will change about us in the next ten years?",
          "Brag about me for a full minute as if I weren't in the room.",
          "Which of our routines feels dead to you, and what should replace it this month?",
          "Send me the message right now that you've been rehearsing in your head for weeks.",
          "Tell me something true about your day that you would normally file under 'not worth mentioning'.",
          "Where do I keep failing you in the same way, and how do you want me to catch it earlier?",
          "If we met again this year, as we are now, would you choose me? Say why, in detail.",
        ],
      },
      {
        labels: [
          "Body",
          "Time",
          "Ghosts",
          "Home",
          "Play",
          "Doubt",
          "Ritual",
          "Ask",
          "Dare",
          "Anger",
          "Growth",
          "Vow",
        ],
        prompts: [
          "What has changed about your body in the last five years, and what do you need from me about it?",
          "Where does our time actually go each week — and which hours would you fight to protect?",
          "Is there anyone from your past you still think about? Tell the truth kindly.",
          "What single thing would make our home feel more like ours and less like a place we store our stuff?",
          "When did we last genuinely play together? What would playing look like this weekend?",
          "What's a doubt about us you've never voiced because saying it might make it real?",
          "Invent one ritual we start tonight and keep for a year. Say the exact rule.",
          "Ask me for something you've never had the nerve to ask for. I answer honestly, no negotiation yet.",
          "Say the sentence you'd want me to remember if you couldn't speak to me for a year.",
          "What made you angry at me recently that you swallowed? Unswallow it now, gently.",
          "Which version of me have you watched grow, and which version are you still waiting for?",
          "What will you personally do differently for the next 90 days so we're better than today?",
        ],
      },
    ],
  },
  {
    id: "purpose",
    name: "Life & Purpose",
    tagline: "For anyone auditing the life they're actually living",
    blurb: "Twelve prompts on ambition, fear, legacy and the person you keep postponing.",
    colors: ["#3f6b57", "#5b7f5a", "#2f5d63", "#7a8f4e", "#456b7a", "#6a8a5f"],
    weeks: [
      {
        labels: [
          "Legacy",
          "Fear",
          "Craft",
          "Money",
          "Time",
          "Regret",
          "Courage",
          "Body",
          "People",
          "Joy",
          "Reset",
          "Vow",
        ],
        prompts: [
          "If someone described your life in one sentence at your 80th birthday, what sentence do you want — and how far off are you?",
          "Name the fear that has quietly made the last three big decisions for you.",
          "What work would you still do if nobody ever saw it, praised it, or paid for it?",
          "How much money is actually 'enough' for you — say a number, then defend it.",
          "Where did the last seven days go? Account for them honestly, hour blocks and all.",
          "What's the door you didn't walk through, and would you walk through it now if it reopened?",
          "What's the bravest thing you could do this week that would take under ten minutes?",
          "What is your body trying to tell you that you've been outsourcing to caffeine and willpower?",
          "Who are the three people shaping you right now — and did you choose them on purpose?",
          "When did you last lose track of time doing something joyful? How do you get more of that?",
          "If you deleted one commitment from your life tomorrow with zero consequences, which one goes?",
          "Say out loud one thing you will start before this month ends — and name who will hold you to it.",
        ],
      },
      {
        labels: [
          "Identity",
          "Envy",
          "Input",
          "Standards",
          "Rest",
          "Risk",
          "Voice",
          "Place",
          "Faith",
          "Waste",
          "Mentor",
          "Line",
        ],
        prompts: [
          "Who are you when nobody needs anything from you? Describe that person in detail.",
          "Whose life makes you quietly envious? Envy is data — what is it pointing at?",
          "What are you consuming daily that is shaping your thinking more than you'd like to admit?",
          "Where are you accepting a standard from yourself you'd never accept from someone you manage?",
          "What does real rest look like for you — not scrolling, not numbing? When did you last have it?",
          "What is the biggest risk you could take this year that wouldn't ruin you if it failed?",
          "What opinion do you hold that you keep softening in public? Say the unsoftened version.",
          "Are you living in the right city, house, and room for the life you say you want?",
          "What do you believe in that you can't prove, and how does it change your behaviour?",
          "Where is your energy leaking? Name the top three drains by hours per week.",
          "Who should be mentoring you right now, and what's stopping you from asking this week?",
          "Draw a line you will not cross this year, no matter the money or the pressure. Say it out loud.",
        ],
      },
      {
        labels: [
          "Death",
          "Story",
          "Skill",
          "Habit",
          "Debt",
          "Comfort",
          "Purpose",
          "Anger",
          "Service",
          "Focus",
          "Proof",
          "Start",
        ],
        prompts: [
          "If you had two good years left, what would you stop doing on Monday?",
          "What story about yourself are you still telling that stopped being true years ago?",
          "What skill, learned over 12 months, would change your options the most?",
          "Which single daily habit, if you were perfect at it for a year, would transform your life?",
          "What debt — money, favours, apologies, or promises — are you carrying that needs clearing?",
          "Where has comfort quietly become the main thing you're optimising for?",
          "Finish it: 'The work I'm supposed to be doing with my life looks something like…'",
          "What injustice reliably makes you angry? What have you actually done about it?",
          "Who benefits when you succeed, besides you? If nobody, is that the problem?",
          "If you could only make progress on one area for six months, which one and why that one?",
          "What evidence from the last 90 days proves you're serious about your stated goals?",
          "Name the first concrete action, doable in 24 hours, and commit to a time you'll do it.",
        ],
      },
    ],
  },
  {
    id: "founder",
    name: "Founder & Operator",
    tagline: "For the person already running the thing",
    blurb:
      "Twelve prompts on the business you're operating right now — cash, customers, hires and the hard call you're avoiding.",
    colors: ["#7a4a1f", "#96601f", "#5c4a7a", "#8a5a2b", "#4a5c8a", "#a06a2c"],
    weeks: [
      {
        labels: [
          "Runway",
          "Customer",
          "Pricing",
          "Team",
          "Bottleneck",
          "Focus",
          "Rival",
          "Delegate",
          "Numbers",
          "Failure",
          "Bet",
          "Exit",
        ],
        prompts: [
          "How many months of runway do you actually have — say the number, then say what you'd cut first if it halved tomorrow.",
          "Name your last customer who churned. Why did they really leave, in their words, not yours?",
          "If you raised prices 30% tonight, who leaves and why is that secretly fine?",
          "Who on your team would you not hire again today — and what has stopped you from acting on that?",
          "What is the single bottleneck in your business right now, and is it a process, a person, or you?",
          "List everything you worked on last week, then cross off anything that didn't move revenue or retention. What's left?",
          "What is a competitor doing better than you, and what would it cost to close that gap this quarter?",
          "Name one task you're still doing that costs less than your hourly rate to hand off. Who gets it this week?",
          "Say your gross margin, CAC and monthly burn out loud from memory. What did you have to guess?",
          "Describe your most expensive mistake this year and the rule you wrote so it can't repeat.",
          "What's the one bet that, if it works, makes the next 12 months easy — and how much are you truly resourcing it?",
          "If someone offered to buy you out today, what number would you say yes to — and what does that number say about your belief?",
        ],
      },
      {
        labels: [
          "Demand",
          "Cash",
          "Churn",
          "Hiring",
          "Systems",
          "Brand",
          "Sales",
          "Product",
          "Risk",
          "Culture",
          "Speed",
          "Cut",
        ],
        prompts: [
          "Where does your next 10 customers come from, specifically? Name the channel and the number.",
          "What is your cash conversion cycle — how long between spending money and getting it back?",
          "Which customer segment retains best, and why aren't you spending all your effort there?",
          "What's the role you most need to hire, and what would it cost you to wait another six months?",
          "Which part of your operation only works because you personally intervene? Document it or lose it.",
          "If a stranger described your company in one line, what would they say? Is that what you want?",
          "How many sales conversations did you personally have last week? Say the number without excuses.",
          "What feature or service do customers ask for that you keep refusing? Is refusing still right?",
          "What single event would kill this business in 90 days, and what's your hedge against it?",
          "What behaviour do you tolerate in your team that quietly contradicts what you say you value?",
          "What decision has been sitting open for more than two weeks? Decide it before this timer ends.",
          "Name the project you should kill today. What is keeping it alive — ego, sunk cost, or hope?",
        ],
      },
      {
        labels: [
          "Truth",
          "Margin",
          "Leverage",
          "Retention",
          "Owner",
          "Story",
          "Partner",
          "Ops",
          "Data",
          "Energy",
          "Moat",
          "Next",
        ],
        prompts: [
          "What number in your business are you avoiding looking at? Say it, or admit you don't know it.",
          "Which product line is subsidising the others? What happens if you kill the losers?",
          "Where can you get 10x output from the same input — code, content, capital, or people?",
          "What happens on day 1, day 7 and day 30 for a new customer? Is any of it deliberate?",
          "If you disappeared for 30 days, what breaks first? Fix that thing this month.",
          "Pitch your business in 30 seconds to someone who's never heard of it. Was it clear or clever?",
          "Who is the one partnership that could double your distribution, and have you actually asked?",
          "Which recurring meeting or report could be deleted with no consequence? Delete it this week.",
          "What's the one metric you'd put on a wall for the whole team, and why that one?",
          "Which part of the work drains you most, and is that a signal to fix, hire, or exit?",
          "Why can't a well-funded copycat beat you in 12 months? Answer honestly.",
          "What is the single most valuable thing you could do tomorrow morning before 10am?",
        ],
      },
    ],
  },
  {
    id: "friendship",
    name: "Friendship & Community",
    tagline: "For the people you choose and the ones who choose you",
    blurb: "Twelve prompts on loyalty, loneliness, chosen family and the friendships you're actually tending.",
    colors: ["#2c4a6b", "#3d5c78", "#4a7a8a", "#3a6b6b", "#5a8a9a", "#2f5a7a"],
    weeks: [
      {
        labels: [
          "Loyalty",
          "Loneliness",
          "Chosen",
          "Conflict",
          "History",
          "Distance",
          "Trust",
          "Envy",
          "Vulnerability",
          "Ritual",
          "Forgiveness",
          "Future",
        ],
        prompts: [
          "Who is the friend you can call at 3am — and when did you last prove that to them?",
          "Describe a time a friend showed up for you in a way that family never could.",
          "What's the friendship you thought would last forever that quietly faded? What happened?",
          "Name one friend you're secretly jealous of. What do they have that you want?",
          "When did you last let a friend see you truly upset — not performatively, not briefly?",
          "Who in your life feels like chosen family, and what makes them family instead of just a friend?",
          "What's the small thing a friend did that you never told them hurt you?",
          "How many of your friendships are kept alive by you initiating, and which ones would disappear if you stopped?",
          "What's the version of yourself you only show around one specific friend?",
          "Describe the ritual, however tiny, that keeps your closest friendship alive.",
          "Who do you owe an apology to but haven't found the words? What would you say?",
          "Picture your life in ten years. Which three people do you hope are still in it, and what will you have to do to keep them there?",
        ],
      },
      {
        labels: [
          "Circle",
          "Effort",
          "Boundary",
          "Repair",
          "Belong",
          "Help",
          "Honesty",
          "Change",
          "Group",
          "Time",
          "Grief",
          "Invite",
        ],
        prompts: [
          "List the five people you spoke to most this month. Is that the circle you want?",
          "Which friendship are you coasting on? What would tending it actually require?",
          "Where do you need a boundary with a friend, and what have you been afraid would happen?",
          "Who drifted away because of something you did? Are you willing to name it out loud?",
          "Where do you feel most like you belong — and how often do you actually go there?",
          "When did you last ask a friend for real help, not a favour? Why is asking hard?",
          "What have you been pretending to agree with to keep the peace in a friendship?",
          "Which friend has changed in a way you haven't adjusted to yet?",
          "In your friend group, what role do you play — and did you pick it or get assigned it?",
          "How much unhurried time have you spent with a friend this month? Say the honest hours.",
          "Who have you lost — to death, distance, or fallout — that you still talk to in your head?",
          "Who will you invite to something specific this week? Name the person, the plan, and the day.",
        ],
      },
      {
        labels: [
          "New",
          "Depth",
          "Money",
          "Jealousy",
          "Show up",
          "Truth",
          "Old",
          "Digital",
          "Give",
          "Ask",
          "Repair",
          "Keep",
        ],
        prompts: [
          "When did you last make a genuinely new friend? What would it take to do it again this year?",
          "Which friendship is stuck at small talk, and what question could break through it?",
          "Has money ever changed a friendship of yours? Tell the story honestly.",
          "Whose success is hardest for you to celebrate, and what does that reveal about you?",
          "Name a friend going through something right now. What will you do about it in the next 48 hours?",
          "What's a truth a friend needs to hear from you that nobody else will say?",
          "Which old friend knows the version of you that you miss most?",
          "How much of your friendship life happens only through screens? Is that enough for you?",
          "What do you reliably give your friends? Ask yourself whether they'd say the same thing.",
          "What do you wish your friends would ask you about but never do?",
          "Whose message have you left unanswered for weeks, and why really?",
          "Choose one friendship to invest in for the next 90 days and say exactly how.",
        ],
      },
    ],
  },
  {
    id: "money",
    name: "Money & Hustle",
    tagline: "For the side hustle you keep talking about",
    blurb: "Twelve prompts on picking an idea, starting small, getting paid, and finishing what you start.",
    colors: ["#8a6a2e", "#a68435", "#4d5c3a", "#7a5c2a", "#3d4a30", "#b8923c"],
    weeks: [
      {
        labels: [
          "Idea",
          "Pick",
          "Start",
          "Finish",
          "Money",
          "Discipline",
          "Fear",
          "Customer",
          "Proof",
          "Time",
          "Skill",
          "Scale",
        ],
        prompts: [
          "What is a skill you already have that someone has paid for, or asked you to do, even once?",
          "Name three side hustles you've flirted with. Which one would you actually start today if you had to pick in 60 seconds?",
          "What is the smallest version of your idea that you could ship this weekend for under $50 and 10 hours?",
          "What is the real reason you haven't finished the last money-making thing you started — boredom, fear, or no customer?",
          "How much money, exact number, would this hustle need to make in month three to feel worth your time?",
          "What daily habit is currently eating the time and energy your hustle needs?",
          "What are you afraid people will say when you finally ask them to pay you for this?",
          "Who is the exact person most likely to pay for this? Describe them in one sentence.",
          "What proof do you have that anyone wants this, beyond your own belief?",
          "If you could only work on this for 30 minutes a day for the next month, what single action would you repeat?",
          "What skill gap is actually stopping you — and what's the fastest way to close it or outsource it?",
          "What would it look like to 'finish' this idea in the next 90 days, and what would you kill to make that happen?",
        ],
      },
      {
        labels: [
          "Price",
          "Offer",
          "Ask",
          "Cash",
          "Waste",
          "System",
          "Excuse",
          "Sell",
          "Feedback",
          "Focus",
          "Save",
          "Ship",
        ],
        prompts: [
          "Say your price out loud right now. Did you flinch? Why?",
          "Describe your offer in one sentence: who it's for, what they get, and what it costs.",
          "Who are three people you could message tonight with a direct offer? Name them.",
          "Where is money already leaking out of your life each month that could fund this instead?",
          "How many hours last week went to preparing versus actually selling? Be exact.",
          "What part of your hustle happens only when you feel motivated? How do you make it a rule instead?",
          "What's your favourite excuse? Say it out loud, then say why it's not true anymore.",
          "When did you last directly ask someone for money for your work? What happened?",
          "Who told you no, and what did you learn from it instead of avoiding it?",
          "You have to delete two of your three projects. Which survives and why?",
          "If this hustle made $500 next month, where would every dollar go?",
          "What can you put in front of a real customer in the next 7 days, even if it's ugly?",
        ],
      },
      {
        labels: [
          "Numbers",
          "Niche",
          "Reps",
          "Content",
          "Trust",
          "Speed",
          "Quit",
          "Leverage",
          "Habit",
          "Support",
          "Ceiling",
          "Vow",
        ],
        prompts: [
          "Say your revenue, costs and profit for last month from memory. What did you not know?",
          "Who are you serving so specifically that they'd feel stupid buying from anyone else?",
          "How many reps have you actually done — pitches, posts, calls, products? Is the number embarrassing?",
          "What would you post publicly this week if you weren't worried about who's watching?",
          "Why should a stranger trust you with their money? Answer as if to their face.",
          "What has taken you a month that a serious person would have done in a weekend?",
          "What are you doing purely because you're afraid to admit it isn't working?",
          "What asset — audience, list, code, tool, relationship — could keep earning while you sleep?",
          "Design the exact 60-minute block you will repeat five days a week. When, where, doing what?",
          "Who is holding you accountable? If nobody, who will you ask before the end of today?",
          "What's the honest ceiling on this hustle, and are you fine with it?",
          "Say the one sentence commitment you'd be embarrassed to break, and name the deadline.",
        ],
      },
    ],
  },
];

/** ISO-ish week index since epoch — changes every Monday. */
export function currentWeekIndex(date: Date = new Date()): number {
  const epochMonday = Date.UTC(1970, 0, 5); // Mon, 5 Jan 1970
  const days = Math.floor((date.getTime() - epochMonday) / 86_400_000);
  return Math.floor(days / 7);
}

export function getWeekSet(deck: Deck, weekIndex: number): PromptSet {
  return deck.weeks[((weekIndex % deck.weeks.length) + deck.weeks.length) % deck.weeks.length]!;
}

/** Monday 00:00 UTC that starts the given week index. */
export function weekStart(weekIndex: number): Date {
  return new Date(Date.UTC(1970, 0, 5) + weekIndex * 7 * 86_400_000);
}
